In [58]:
import pandas as pd

In [59]:
import numpy as np

In [60]:
df = pd.read_csv('C:/Users/paree/Documents/GermanCreditDataset/SouthGermanCredit.asc', sep=" ")

# Data Import

We imported data using read_csv command

In [61]:
type(df)

pandas.core.frame.DataFrame

This tells us that df is an object of type DataFrame i.e. it belongs to the class DataFrame

In [62]:
df.index

RangeIndex(start=0, stop=1000, step=1)

Index is a label not a row number

If we use the drop() func, it doesn't reset the index unless mentioned

In [63]:
type(df.index)

pandas.core.indexes.range.RangeIndex

This tells that this index is of type RangeIndex (where index is sequential, starts from 0 and increases step wise)

Pandas has multiple types of Indexes (int64, float64, datetime)

In [64]:
df.loc[5]

laufkont       1
laufzeit      10
moral          4
verw           0
hoehe       2241
sparkont       1
beszeit        2
rate           1
famges         3
buerge         1
wohnzeit       3
verm           1
alter         48
weitkred       3
wohn           1
bishkred       2
beruf          2
pers           1
telef          1
gastarb        1
kredit         1
Name: 5, dtype: int64

loc is label based, it cares about the index.. It gave us the row whose index is 5

In [65]:
df.iloc[5]

laufkont       1
laufzeit      10
moral          4
verw           0
hoehe       2241
sparkont       1
beszeit        2
rate           1
famges         3
buerge         1
wohnzeit       3
verm           1
alter         48
weitkred       3
wohn           1
bishkred       2
beruf          2
pers           1
telef          1
gastarb        1
kredit         1
Name: 5, dtype: int64

iloc doesnt care about index labels, it is postition based. It gave us the row whose position is 5
Coincidentally in this case both index 5 and position 5 lie at the same spot so both the commands have the same row
iloc is unaffected by index changes

In [66]:
df_new = df.drop(5)

Doesn't modify/drop in the original DataFrame, if we had done df = df.drop(5) then it would have made the change so it is 
not in-place by default
drop command is label/index based

In [67]:
df_new.loc[6]

laufkont       1
laufzeit       8
moral          4
verw           0
hoehe       3398
sparkont       1
beszeit        4
rate           1
famges         3
buerge         1
wohnzeit       4
verm           1
alter         39
weitkred       3
wohn           2
bishkred       2
beruf          2
pers           2
telef          1
gastarb        1
kredit         1
Name: 6, dtype: int64

In [68]:
df_new.iloc[5]

laufkont       1
laufzeit       8
moral          4
verw           0
hoehe       3398
sparkont       1
beszeit        4
rate           1
famges         3
buerge         1
wohnzeit       4
verm           1
alter         39
weitkred       3
wohn           2
bishkred       2
beruf          2
pers           2
telef          1
gastarb        1
kredit         1
Name: 6, dtype: int64

By using the drop command we and then using loc and iloc we can now understand that loc is index based and iloc is position based

In [69]:
#df_new.loc[5]

This gives error now as index 5 is not existing now

In [70]:
df.loc[0:5]

,laufkont,laufzeit,moral,verw,hoehe,sparkont,beszeit,rate,famges,buerge,...,verm,alter,weitkred,wohn,bishkred,beruf,pers,telef,gastarb,kredit
0,1,18,4,2,1049,1,2,4,2,1,...,2,21,3,1,1,3,2,1,2,1
1,1,9,4,0,2799,1,3,2,3,1,...,1,36,3,1,2,3,1,1,2,1
2,2,12,2,9,841,2,4,2,2,1,...,1,23,3,1,1,2,2,1,2,1
3,1,12,4,0,2122,1,3,3,3,1,...,1,39,3,1,2,2,1,1,1,1
4,1,12,4,0,2171,1,3,4,3,1,...,2,38,1,2,2,2,2,1,1,1
5,1,10,4,0,2241,1,2,1,3,1,...,1,48,3,1,2,2,1,1,1,1

In [71]:
df.iloc[0:5]

,laufkont,laufzeit,moral,verw,hoehe,sparkont,beszeit,rate,famges,buerge,...,verm,alter,weitkred,wohn,bishkred,beruf,pers,telef,gastarb,kredit
0,1,18,4,2,1049,1,2,4,2,1,...,2,21,3,1,1,3,2,1,2,1
1,1,9,4,0,2799,1,3,2,3,1,...,1,36,3,1,2,3,1,1,2,1
2,2,12,2,9,841,2,4,2,2,1,...,1,23,3,1,1,2,2,1,2,1
3,1,12,4,0,2122,1,3,3,3,1,...,1,39,3,1,2,2,1,1,1,1
4,1,12,4,0,2171,1,3,4,3,1,...,2,38,1,2,2,2,2,1,1,1

Observe that loc returned 6 rows and iloc returned 5 rows with the same slicing parameter
This is because loc is slicing inclusive
While iloc is slicing exclusive (like normal Python slicing)

In [72]:
mask = df['alter'] > 50

In [73]:
type(mask)

pandas.core.series.Series

In [74]:
mask.head()

0    False
1    False
2    False
3    False
4    False
Name: alter, dtype: bool

Pandas compare each value in column alter, produces a Series of True/False and 
align it with the original index. This is called Boolean Series.

In [75]:
mask.tail()

995    False
996    False
997    False
998     True
999    False
Name: alter, dtype: bool

In [76]:
df['alter'].head()

0    21
1    36
2    23
3    39
4    38
Name: alter, dtype: int64

In [77]:
df['alter'].iloc[0:5]

0    21
1    36
2    23
3    39
4    38
Name: alter, dtype: int64

In [78]:
df[mask]

,laufkont,laufzeit,moral,verw,hoehe,sparkont,beszeit,rate,famges,buerge,...,verm,alter,weitkred,wohn,bishkred,beruf,pers,telef,gastarb,kredit
8,4,18,4,3,1098,1,1,4,2,1,...,3,65,3,2,2,1,2,1,2,1
25,2,11,3,3,4771,1,4,2,3,1,...,2,51,3,2,1,3,2,1,2,1
29,3,42,4,1,4796,1,5,4,3,1,...,4,56,3,3,1,3,2,1,2,1
41,1,24,2,10,1755,1,5,4,2,3,...,1,58,3,2,1,2,2,2,2,1
44,2,18,2,6,1239,5,3,4,3,1,...,4,61,3,3,1,3,2,1,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
960,4,18,2,0,6761,5,3,2,3,1,...,3,68,2,1,2,3,2,1,2,0
962,2,54,0,9,15945,1,2,3,3,1,...,4,58,3,1,1,3,2,2,2,0
977,1,6,2,0,14896,1,5,1,3,1,...,4,68,1,2,1,4,2,2,2,0
992,1,18,2,1,7511,5,5,1,3,1,...,2,51,3,3,1,3,1,2,2,0
998,2,12,2,3,6468,5,1,2,3,1,...,4,52,3,2,1,4,2,2,2,0

Returns rows where mask == True without any loops or manual iteration.

In [79]:
mask.index.equals(df.index)

True

In [80]:
mask.sum()

113

This gave how many rows satisfied the condition given with mask, as True = 1
and False= 0

In [81]:
df[df['alter'] > 5]['alter'].head()

0    21
1    36
2    23
3    39
4    38
Name: alter, dtype: int64

This is Boolean Indexing. 
Boolean Indexing = filtering rows using True/False conditions.
A condition produces a Boolean Series

In [82]:
df[df['alter']>20]

,laufkont,laufzeit,moral,verw,hoehe,sparkont,beszeit,rate,famges,buerge,...,verm,alter,weitkred,wohn,bishkred,beruf,pers,telef,gastarb,kredit
0,1,18,4,2,1049,1,2,4,2,1,...,2,21,3,1,1,3,2,1,2,1
1,1,9,4,0,2799,1,3,2,3,1,...,1,36,3,1,2,3,1,1,2,1
2,2,12,2,9,841,2,4,2,2,1,...,1,23,3,1,1,2,2,1,2,1
3,1,12,4,0,2122,1,3,3,3,1,...,1,39,3,1,2,2,1,1,1,1
4,1,12,4,0,2171,1,3,4,3,1,...,2,38,1,2,2,2,2,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1,24,2,3,1987,1,3,2,3,1,...,1,21,3,1,1,2,1,1,2,0
996,1,24,2,0,2303,1,5,4,3,2,...,1,45,3,2,1,3,2,1,2,0
997,4,21,4,0,12680,5,5,4,3,1,...,4,30,3,3,1,4,2,2,2,0
998,2,12,2,3,6468,5,1,2,3,1,...,4,52,3,2,1,4,2,2,2,0
999,1,30,2,2,6350,5,5,4,3,1,...,2,31,3,2,1,3,2,1,2,0

In [83]:
df.columns

Index(['laufkont', 'laufzeit', 'moral', 'verw', 'hoehe', 'sparkont', 'beszeit',
       'rate', 'famges', 'buerge', 'wohnzeit', 'verm', 'alter', 'weitkred',
       'wohn', 'bishkred', 'beruf', 'pers', 'telef', 'gastarb', 'kredit'],
      dtype='object')

In [84]:
df.columns.tolist()

['laufkont',
 'laufzeit',
 'moral',
 'verw',
 'hoehe',
 'sparkont',
 'beszeit',
 'rate',
 'famges',
 'buerge',
 'wohnzeit',
 'verm',
 'alter',
 'weitkred',
 'wohn',
 'bishkred',
 'beruf',
 'pers',
 'telef',
 'gastarb',
 'kredit']

In [85]:
df['hoehe'] > 1000

0       True
1       True
2      False
3       True
4       True
       ...
995     True
996     True
997     True
998     True
999     True
Name: hoehe, Length: 1000, dtype: bool

In [86]:
df[df['hoehe'] > 1000]

,laufkont,laufzeit,moral,verw,hoehe,sparkont,beszeit,rate,famges,buerge,...,verm,alter,weitkred,wohn,bishkred,beruf,pers,telef,gastarb,kredit
0,1,18,4,2,1049,1,2,4,2,1,...,2,21,3,1,1,3,2,1,2,1
1,1,9,4,0,2799,1,3,2,3,1,...,1,36,3,1,2,3,1,1,2,1
3,1,12,4,0,2122,1,3,3,3,1,...,1,39,3,1,2,2,1,1,1,1
4,1,12,4,0,2171,1,3,4,3,1,...,2,38,1,2,2,2,2,1,1,1
5,1,10,4,0,2241,1,2,1,3,1,...,1,48,3,1,2,2,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1,24,2,3,1987,1,3,2,3,1,...,1,21,3,1,1,2,1,1,2,0
996,1,24,2,0,2303,1,5,4,3,2,...,1,45,3,2,1,3,2,1,2,0
997,4,21,4,0,12680,5,5,4,3,1,...,4,30,3,3,1,4,2,2,2,0
998,2,12,2,3,6468,5,1,2,3,1,...,4,52,3,2,1,4,2,2,2,0
999,1,30,2,2,6350,5,5,4,3,1,...,2,31,3,2,1,3,2,1,2,0

In [87]:
for col in df.columns:
    print(col)

laufkont
laufzeit
moral
verw
hoehe
sparkont
beszeit
rate
famges
buerge
wohnzeit
verm
alter
weitkred
wohn
bishkred
beruf
pers
telef
gastarb
kredit

In [88]:
df[(df['alter'] > 25) & (df['hoehe'] < 1000)]

,laufkont,laufzeit,moral,verw,hoehe,sparkont,beszeit,rate,famges,buerge,...,verm,alter,weitkred,wohn,bishkred,beruf,pers,telef,gastarb,kredit
35,1,6,4,0,860,1,5,1,2,1,...,4,39,3,2,2,3,2,2,2,1
50,4,12,2,0,640,1,3,4,1,1,...,1,49,3,2,1,2,2,1,2,1
55,1,12,4,3,385,1,4,4,2,1,...,1,58,3,2,4,2,2,2,2,1
73,4,24,2,2,929,5,4,4,3,1,...,3,31,2,2,1,3,2,2,2,1
88,1,6,4,0,666,4,4,3,2,1,...,1,39,3,2,2,2,2,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
949,4,12,4,3,797,5,5,4,2,1,...,2,33,3,2,1,2,1,1,2,0
951,3,12,4,0,939,3,4,4,4,1,...,1,28,3,2,3,3,2,2,2,0
954,3,12,1,9,609,1,2,4,2,1,...,1,26,1,2,1,1,2,1,2,0
964,2,15,2,3,802,1,5,4,3,1,...,3,37,3,2,1,3,1,1,2,0
990,1,18,2,6,750,1,1,4,2,1,...,1,27,3,2,1,1,2,1,2,0

The syntax is:
    df[(condition1) & (condition2)]

In [89]:
df[df['alter'].between (20,30)]

,laufkont,laufzeit,moral,verw,hoehe,sparkont,beszeit,rate,famges,buerge,...,verm,alter,weitkred,wohn,bishkred,beruf,pers,telef,gastarb,kredit
0,1,18,4,2,1049,1,2,4,2,1,...,2,21,3,1,1,3,2,1,2,1
2,2,12,2,9,841,2,4,2,2,1,...,1,23,3,1,1,2,2,1,2,1
9,2,24,2,3,3758,3,1,1,2,1,...,4,23,3,1,1,1,2,1,2,1
11,1,30,4,1,6187,2,4,1,4,1,...,3,24,3,1,2,3,2,1,2,1
14,1,18,2,3,1936,5,4,2,4,1,...,3,23,3,1,2,2,2,1,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
989,2,24,2,0,2718,1,3,3,2,1,...,2,20,3,1,1,2,2,2,2,0
990,1,18,2,6,750,1,1,4,2,1,...,1,27,3,2,1,1,2,1,2,0
994,1,12,0,3,6199,1,3,4,3,1,...,2,28,3,1,2,3,2,2,2,0
995,1,24,2,3,1987,1,3,2,3,1,...,1,21,3,1,1,2,1,1,2,0
997,4,21,4,0,12680,5,5,4,3,1,...,4,30,3,3,1,4,2,2,2,0

In [90]:
df.isnull()

,laufkont,laufzeit,moral,verw,hoehe,sparkont,beszeit,rate,famges,buerge,...,verm,alter,weitkred,wohn,bishkred,beruf,pers,telef,gastarb,kredit
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

***************************************
Boolean indexing is used for:
    Train-test split logic
    Feature filtering
    Outlier removal
    Condition-based transformation
    Creating target segments
    EDA slicing

***************************************

Pandas filtering, creates a copy not view
It can increase memory usage
So use .loc[] for clarity

In [91]:
df.loc[df['alter'] > 20]

,laufkont,laufzeit,moral,verw,hoehe,sparkont,beszeit,rate,famges,buerge,...,verm,alter,weitkred,wohn,bishkred,beruf,pers,telef,gastarb,kredit
0,1,18,4,2,1049,1,2,4,2,1,...,2,21,3,1,1,3,2,1,2,1
1,1,9,4,0,2799,1,3,2,3,1,...,1,36,3,1,2,3,1,1,2,1
2,2,12,2,9,841,2,4,2,2,1,...,1,23,3,1,1,2,2,1,2,1
3,1,12,4,0,2122,1,3,3,3,1,...,1,39,3,1,2,2,1,1,1,1
4,1,12,4,0,2171,1,3,4,3,1,...,2,38,1,2,2,2,2,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1,24,2,3,1987,1,3,2,3,1,...,1,21,3,1,1,2,1,1,2,0
996,1,24,2,0,2303,1,5,4,3,2,...,1,45,3,2,1,3,2,1,2,0
997,4,21,4,0,12680,5,5,4,3,1,...,4,30,3,3,1,4,2,2,2,0
998,2,12,2,3,6468,5,1,2,3,1,...,4,52,3,2,1,4,2,2,2,0
999,1,30,2,2,6350,5,5,4,3,1,...,2,31,3,2,1,3,2,1,2,0

df[df['alter']] , gives error because this works only with Boolean column

In [92]:
df.sort_values('alter')

,laufkont,laufzeit,moral,verw,hoehe,sparkont,beszeit,rate,famges,buerge,...,verm,alter,weitkred,wohn,bishkred,beruf,pers,telef,gastarb,kredit
819,4,9,2,2,1980,1,2,2,2,2,...,3,19,3,1,2,3,2,1,2,0
298,2,12,2,2,983,4,2,1,2,1,...,1,19,3,1,1,2,2,1,2,1
554,2,11,2,2,1577,4,2,4,2,1,...,1,20,3,2,1,3,2,1,2,1
662,2,12,3,3,585,1,3,4,4,2,...,1,20,3,1,2,3,2,1,2,1
514,4,15,2,0,3186,4,4,2,2,1,...,3,20,3,1,1,3,2,1,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
213,3,6,4,0,1299,1,3,1,3,1,...,1,74,3,2,3,1,1,1,1,1
167,4,24,4,9,4526,1,3,3,3,1,...,1,74,3,2,1,4,2,2,2,1
259,4,5,2,9,3448,1,4,1,3,1,...,1,74,3,2,1,2,2,1,2,1
602,1,6,2,0,1374,5,1,4,2,1,...,2,75,3,2,1,4,2,2,2,1
624,1,24,4,1,6615,1,1,2,3,1,...,4,75,3,3,2,4,2,2,2,1

In [93]:
df.sort_values('alter', ascending=False)

,laufkont,laufzeit,moral,verw,hoehe,sparkont,beszeit,rate,famges,buerge,...,verm,alter,weitkred,wohn,bishkred,beruf,pers,telef,gastarb,kredit
624,1,24,4,1,6615,1,1,2,3,1,...,4,75,3,3,2,4,2,2,2,1
602,1,6,2,0,1374,5,1,4,2,1,...,2,75,3,2,1,4,2,2,2,1
167,4,24,4,9,4526,1,3,3,3,1,...,1,74,3,2,1,4,2,2,2,1
814,2,9,1,1,5129,1,5,2,2,1,...,4,74,1,3,1,4,1,2,2,0
213,3,6,4,0,1299,1,3,1,3,1,...,1,74,3,2,3,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
514,4,15,2,0,3186,4,4,2,2,1,...,3,20,3,1,1,3,2,1,2,1
535,2,24,2,3,1967,1,5,4,2,1,...,3,20,3,2,1,3,2,2,2,1
206,1,12,2,3,1107,1,3,2,3,1,...,1,20,3,1,1,4,1,2,2,1
298,2,12,2,2,983,4,2,1,2,1,...,1,19,3,1,1,2,2,1,2,1
819,4,9,2,2,1980,1,2,2,2,2,...,3,19,3,1,2,3,2,1,2,0

In [94]:
df.sort_values('hoehe', ascending=False)

,laufkont,laufzeit,moral,verw,hoehe,sparkont,beszeit,rate,famges,buerge,...,verm,alter,weitkred,wohn,bishkred,beruf,pers,telef,gastarb,kredit
976,2,48,0,10,18424,1,3,1,2,1,...,2,32,1,2,1,4,2,2,1,0
962,2,54,0,9,15945,1,2,3,3,1,...,4,58,3,1,1,3,2,2,2,0
645,1,36,2,10,15857,1,1,2,1,2,...,3,43,3,2,1,4,2,1,2,1
810,2,48,2,9,15672,1,3,2,3,1,...,3,23,3,2,1,3,2,2,2,0
695,4,60,3,3,15653,1,4,2,3,1,...,3,21,3,2,2,3,2,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
373,1,6,2,4,343,1,2,4,2,1,...,1,27,3,2,1,3,2,1,2,1
300,1,12,1,8,339,1,5,4,4,1,...,3,45,1,2,1,2,2,1,2,1
286,1,6,4,3,338,3,5,4,3,1,...,3,52,3,2,2,3,2,1,2,1
383,2,9,2,0,276,1,3,4,4,1,...,1,22,3,1,1,2,2,1,2,1
312,4,6,4,0,250,4,3,2,2,1,...,1,41,1,2,2,2,2,1,2,1

In [95]:
df.sort_values(['hoehe','alter'], ascending=[False,True])

,laufkont,laufzeit,moral,verw,hoehe,sparkont,beszeit,rate,famges,buerge,...,verm,alter,weitkred,wohn,bishkred,beruf,pers,telef,gastarb,kredit
976,2,48,0,10,18424,1,3,1,2,1,...,2,32,1,2,1,4,2,2,1,0
962,2,54,0,9,15945,1,2,3,3,1,...,4,58,3,1,1,3,2,2,2,0
645,1,36,2,10,15857,1,1,2,1,2,...,3,43,3,2,1,4,2,1,2,1
810,2,48,2,9,15672,1,3,2,3,1,...,3,23,3,2,1,3,2,2,2,0
695,4,60,3,3,15653,1,4,2,3,1,...,3,21,3,2,2,3,2,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
373,1,6,2,4,343,1,2,4,2,1,...,1,27,3,2,1,3,2,1,2,1
300,1,12,1,8,339,1,5,4,4,1,...,3,45,1,2,1,2,2,1,2,1
286,1,6,4,3,338,3,5,4,3,1,...,3,52,3,2,2,3,2,1,2,1
383,2,9,2,0,276,1,3,4,4,1,...,1,22,3,1,1,2,2,1,2,1
312,4,6,4,0,250,4,3,2,2,1,...,1,41,1,2,2,2,2,1,2,1

As there's no duplicates in the primary filter column i.e. 'hoehe' in this case so the filtering was done on basis of 'hoehe' in descending order while the secondary sorting column 'alter's' filter condition of ascending was ignored. This is why we get the same output for this and command before this one.

Multi-column sorting only matters when:

    First column contains duplicates.
    Otherwise secondary columns are irrelevant.

Pandas uses a stable sorting algorithm (Timsort for object / mergesort when specified).
Stable means:
    If two rows have equal values in the sorting column, their original relative order is preserved.

df.sort_values('loan_amount')
Returns a new DataFrame

    Does not mutate df
    Default: inplace=False
It is not “just displaying.”
It is creating a new sorted object.
If we pass inplace=True in the command then it would modify the original

In [96]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   laufkont  1000 non-null   int64
 1   laufzeit  1000 non-null   int64
 2   moral     1000 non-null   int64
 3   verw      1000 non-null   int64
 4   hoehe     1000 non-null   int64
 5   sparkont  1000 non-null   int64
 6   beszeit   1000 non-null   int64
 7   rate      1000 non-null   int64
 8   famges    1000 non-null   int64
 9   buerge    1000 non-null   int64
 10  wohnzeit  1000 non-null   int64
 11  verm      1000 non-null   int64
 12  alter     1000 non-null   int64
 13  weitkred  1000 non-null   int64
 14  wohn      1000 non-null   int64
 15  bishkred  1000 non-null   int64
 16  beruf     1000 non-null   int64
 17  pers      1000 non-null   int64
 18  telef     1000 non-null   int64
 19  gastarb   1000 non-null   int64
 20  kredit    1000 non-null   int64
dtypes: int64(21)
memory usage: 164.2 KB

In [97]:
df.dtypes

laufkont    int64
laufzeit    int64
moral       int64
verw        int64
hoehe       int64
sparkont    int64
beszeit     int64
rate        int64
famges      int64
buerge      int64
wohnzeit    int64
verm        int64
alter       int64
weitkred    int64
wohn        int64
bishkred    int64
beruf       int64
pers        int64
telef       int64
gastarb     int64
kredit      int64
dtype: object

Even though all columns have an int64 data types, not all are inherently numeric. Some have been label encoded.

We will be converting few columns to category even before modelling because:
    1. It reduces memory usage
    2. Makes intent explicit
    3. Speeds up groupby
    4. Prevents accidental numeric operations on categorical columns.

In [98]:
df.memory_usage(deep=True)

Index        132
laufkont    8000
laufzeit    8000
moral       8000
verw        8000
hoehe       8000
sparkont    8000
beszeit     8000
rate        8000
famges      8000
buerge      8000
wohnzeit    8000
verm        8000
alter       8000
weitkred    8000
wohn        8000
bishkred    8000
beruf       8000
pers        8000
telef       8000
gastarb     8000
kredit      8000
dtype: int64

In [99]:
df['verw'] = df['verw'].astype('category')

Converted the 'verw' column to category.

In [100]:
df.dtypes

laufkont       int64
laufzeit       int64
moral          int64
verw        category
hoehe          int64
sparkont       int64
beszeit        int64
rate           int64
famges         int64
buerge         int64
wohnzeit       int64
verm           int64
alter          int64
weitkred       int64
wohn           int64
bishkred       int64
beruf          int64
pers           int64
telef          int64
gastarb        int64
kredit         int64
dtype: object

In [101]:
df['beruf'] = df['beruf'].astype('category')

In [102]:
df.dtypes

laufkont       int64
laufzeit       int64
moral          int64
verw        category
hoehe          int64
sparkont       int64
beszeit        int64
rate           int64
famges         int64
buerge         int64
wohnzeit       int64
verm           int64
alter          int64
weitkred       int64
wohn           int64
bishkred       int64
beruf       category
pers           int64
telef          int64
gastarb        int64
kredit         int64
dtype: object

In [103]:
df['wohn'] = df['wohn'].astype('category')

In [104]:
df['buerge'] = df['buerge'].astype('category')

In [105]:
df['weitkred'] = df['weitkred'].astype('category')

In [106]:
df.memory_usage(deep=True)

Index        132
laufkont    8000
laufzeit    8000
moral       8000
verw        1380
hoehe       8000
sparkont    8000
beszeit     8000
rate        8000
famges      8000
buerge      1132
wohnzeit    8000
verm        8000
alter       8000
weitkred    1132
wohn        1132
bishkred    8000
beruf       1204
pers        8000
telef       8000
gastarb     8000
kredit      8000
dtype: int64

In [107]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   laufkont  1000 non-null   int64
 1   laufzeit  1000 non-null   int64
 2   moral     1000 non-null   int64
 3   verw      1000 non-null   category
 4   hoehe     1000 non-null   int64
 5   sparkont  1000 non-null   int64
 6   beszeit   1000 non-null   int64
 7   rate      1000 non-null   int64
 8   famges    1000 non-null   int64
 9   buerge    1000 non-null   category
 10  wohnzeit  1000 non-null   int64
 11  verm      1000 non-null   int64
 12  alter     1000 non-null   int64
 13  weitkred  1000 non-null   category
 14  wohn      1000 non-null   category
 15  bishkred  1000 non-null   int64
 16  beruf     1000 non-null   category
 17  pers      1000 non-null   int64
 18  telef     1000 non-null   int64
 19  gastarb   1000 non-null   int64
 20  kredit    1000 non-null   int64
dtypes: category(5), int64(16)
memory usage: 131.0 KB

We observe that converting these columns resulted in a less overall memory usage by the data frame. Although in small dataset this is a minor change but in real large data sets the benefit is evident.

df['verw'].mean()  wont work as the 'verw' column now is a categorical column

In [108]:
df['verw'].value_counts()

verw
3     280
0     234
2     181
1     103
9      97
6      50
5      22
4      12
10     12
8       9
Name: count, dtype: int64

It still works even for a category column as it counts occurrences of each 
category label and does not assume numeric meaning.

In [109]:
df.groupby('verw')['kredit'].mean()

C:\Users\paree\AppData\Local\Temp\ipykernel_13496\3158908519.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('verw')['kredit'].mean()

verw
0     0.619658
1     0.834951
2     0.679558
3     0.778571
4     0.666667
5     0.636364
6     0.560000
8     0.888889
9     0.649485
10    0.583333
Name: kredit, dtype: float64

This is the default rate by purpose

# Copy vs View and Safe Assignment

In [110]:
subset = df[df['alter'] > 30]
subset['hoehe'] = subset['hoehe'] * 1.1

C:\Users\paree\AppData\Local\Temp\ipykernel_13496\1272941731.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset['hoehe'] = subset['hoehe'] * 1.1

We get the warning on running the above code due to the unpredictibilty whether
the original df changes or not. As it sometimes does changes and sometime it 
does not. Rather modify the original directly using loc.

In [111]:
subset = df.loc[df['alter'] > 30].copy()

In [112]:
subset['hoehe'] *= 1.1

In [113]:
df['hoehe'].dtype

dtype('int64')

In [115]:
df.sum(axis=0, numeric_only=True)

laufkont       2577
laufzeit      20903
moral          2545
hoehe       3271248
sparkont       2105
beszeit        3384
rate           2973
famges         2682
wohnzeit       2845
verm           2358
alter         35542
bishkred       1407
pers           1845
telef          1404
gastarb        1963
kredit          700
dtype: int64

axis = 0 collapses the row and computes result per column
Reduces the dimension.

In [116]:
df.sum(axis=1)

0       1125
1       2876
2        918
3       2204
4       2256
       ...
995     2064
996     2406
997    12782
998     6572
999     6454
Length: 1000, dtype: int64

axis=1 collapses the column and computers result per row but in this case was 
statistically insignificant and created a meaningless mixture.

In [117]:
df.drop('hoehe', axis=1)

,laufkont,laufzeit,moral,verw,sparkont,beszeit,rate,famges,buerge,wohnzeit,verm,alter,weitkred,wohn,bishkred,beruf,pers,telef,gastarb,kredit
0,1,18,4,2,1,2,4,2,1,4,2,21,3,1,1,3,2,1,2,1
1,1,9,4,0,1,3,2,3,1,2,1,36,3,1,2,3,1,1,2,1
2,2,12,2,9,2,4,2,2,1,4,1,23,3,1,1,2,2,1,2,1
3,1,12,4,0,1,3,3,3,1,2,1,39,3,1,2,2,1,1,1,1
4,1,12,4,0,1,3,4,3,1,4,2,38,1,2,2,2,2,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1,24,2,3,1,3,2,3,1,4,1,21,3,1,1,2,1,1,2,0
996,1,24,2,0,1,5,4,3,2,1,1,45,3,2,1,3,2,1,2,0
997,4,21,4,0,5,5,4,3,1,4,4,30,3,3,1,4,2,2,2,0
998,2,12,2,3,5,1,2,3,1,1,4,52,3,2,1,4,2,2,2,0
999,1,30,2,2,5,5,4,3,1,4,2,31,3,2,1,3,2,1,2,0

The drop commands require the column axis to be mentioned when droppin a column because
axis = 0 is the default for the drop command.
Drops returns a separate dataframe with that particular feature removed.

In [118]:
df.drop(6,axis=0)

,laufkont,laufzeit,moral,verw,hoehe,sparkont,beszeit,rate,famges,buerge,...,verm,alter,weitkred,wohn,bishkred,beruf,pers,telef,gastarb,kredit
0,1,18,4,2,1049,1,2,4,2,1,...,2,21,3,1,1,3,2,1,2,1
1,1,9,4,0,2799,1,3,2,3,1,...,1,36,3,1,2,3,1,1,2,1
2,2,12,2,9,841,2,4,2,2,1,...,1,23,3,1,1,2,2,1,2,1
3,1,12,4,0,2122,1,3,3,3,1,...,1,39,3,1,2,2,1,1,1,1
4,1,12,4,0,2171,1,3,4,3,1,...,2,38,1,2,2,2,2,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1,24,2,3,1987,1,3,2,3,1,...,1,21,3,1,1,2,1,1,2,0
996,1,24,2,0,2303,1,5,4,3,2,...,1,45,3,2,1,3,2,1,2,0
997,4,21,4,0,12680,5,5,4,3,1,...,4,30,3,3,1,4,2,2,2,0
998,2,12,2,3,6468,5,1,2,3,1,...,4,52,3,2,1,4,2,2,2,0
999,1,30,2,2,6350,5,5,4,3,1,...,2,31,3,2,1,3,2,1,2,0

In [119]:
df.sort_values('hoehe').head().reset_index()

,index,laufkont,laufzeit,moral,verw,hoehe,sparkont,beszeit,rate,famges,...,verm,alter,weitkred,wohn,bishkred,beruf,pers,telef,gastarb,kredit
0,312,4,6,4,0,250,4,3,2,2,...,1,41,1,2,2,2,2,1,2,1
1,383,2,9,2,0,276,1,3,4,4,...,1,22,3,1,1,2,2,1,2,1
2,286,1,6,4,3,338,3,5,4,3,...,3,52,3,2,2,3,2,1,2,1
3,300,1,12,1,8,339,1,5,4,4,...,3,45,1,2,1,2,2,1,2,1
4,373,1,6,2,4,343,1,2,4,2,...,1,27,3,2,1,3,2,1,2,1

# Method Chaining
Be careful that we dont overwrite the results

In [120]:
df.sort_values('hoehe', ascending=False).head().reset_index()

,index,laufkont,laufzeit,moral,verw,hoehe,sparkont,beszeit,rate,famges,...,verm,alter,weitkred,wohn,bishkred,beruf,pers,telef,gastarb,kredit
0,976,2,48,0,10,18424,1,3,1,2,...,2,32,1,2,1,4,2,2,1,0
1,962,2,54,0,9,15945,1,2,3,3,...,4,58,3,1,1,3,2,2,2,0
2,645,1,36,2,10,15857,1,1,2,1,...,3,43,3,2,1,4,2,1,2,1
3,810,2,48,2,9,15672,1,3,2,3,...,3,23,3,2,1,3,2,2,2,0
4,695,4,60,3,3,15653,1,4,2,3,...,3,21,3,2,2,3,2,2,2,1

In [ ]:
#df.sort_values('hoehe', replace=True).head()

Using replace=True stopped the command from returning a new df so it breaks down because replace=True returns nothing so nothing.head() gives
error.

In [122]:
df.sort_values('hoehe').head().reset_index(drop=True)

,laufkont,laufzeit,moral,verw,hoehe,sparkont,beszeit,rate,famges,buerge,...,verm,alter,weitkred,wohn,bishkred,beruf,pers,telef,gastarb,kredit
0,4,6,4,0,250,4,3,2,2,1,...,1,41,1,2,2,2,2,1,2,1
1,2,9,2,0,276,1,3,4,4,1,...,1,22,3,1,1,2,2,1,2,1
2,1,6,4,3,338,3,5,4,3,1,...,3,52,3,2,2,3,2,1,2,1
3,1,12,1,8,339,1,5,4,4,1,...,3,45,1,2,1,2,2,1,2,1
4,1,6,2,4,343,1,2,4,2,1,...,1,27,3,2,1,3,2,1,2,1

resets the index when we use drop=True

# Vectorization VS Apply

In [123]:
df['new'] = df['hoehe'] * 2

In [124]:
df['new']

0       2098
1       5598
2       1682
3       4244
4       4342
       ...
995     3974
996     4606
997    25360
998    12936
999    12700
Name: new, Length: 1000, dtype: int64

In [125]:
#This was the vectorized way, this is faster and generally used. Works on the entire column at once

In [126]:
df['new'] = df['hoehe'].apply(lambda x: x*3)

In [127]:
df['new']

0       3147
1       8397
2       2523
3       6366
4       6513
       ...
995     5961
996     6909
997    38040
998    19404
999    19050
Name: new, Length: 1000, dtype: int64

In [128]:
#This was the apply method, comparitively slower. Useful when when there's a complex conditonal logic

In [129]:
df['risk'] = df['alter'].apply(lambda x: 1 if x > 50 else 0)

In [130]:
df['risk']

0      0
1      0
2      0
3      0
4      0
      ..
995    0
996    0
997    0
998    1
999    0
Name: risk, Length: 1000, dtype: int64

In [131]:
df.shape

(1000, 23)

In [132]:
df.describe(include='category')

        verw  buerge  weitkred  wohn  beruf
count   1000    1000      1000  1000   1000
unique    10       3         3     3      4
top        3       1         3     2      3
freq     280     907       814   714    630

In [133]:
df.isna().sum()

laufkont    0
laufzeit    0
moral       0
verw        0
hoehe       0
sparkont    0
beszeit     0
rate        0
famges      0
buerge      0
wohnzeit    0
verm        0
alter       0
weitkred    0
wohn        0
bishkred    0
beruf       0
pers        0
telef       0
gastarb     0
kredit      0
new         0
risk        0
dtype: int64

In [134]:
df.nunique()

laufkont      4
laufzeit     33
moral         5
verw         10
hoehe       923
sparkont      5
beszeit       5
rate          4
famges        4
buerge        3
wohnzeit      4
verm          4
alter        53
weitkred      3
wohn          3
bishkred      4
beruf         4
pers          2
telef         2
gastarb       2
kredit        2
new         923
risk          2
dtype: int64

In [135]:
df= df.drop(['new', 'risk'], axis=1)

In [136]:
df.dtypes

laufkont       int64
laufzeit       int64
moral          int64
verw        category
hoehe          int64
sparkont       int64
beszeit        int64
rate           int64
famges         int64
buerge      category
wohnzeit       int64
verm           int64
alter          int64
weitkred    category
wohn        category
bishkred       int64
beruf       category
pers           int64
telef          int64
gastarb        int64
kredit         int64
dtype: object

In [137]:
df.describe(include='category')

        verw  buerge  weitkred  wohn  beruf
count   1000    1000      1000  1000   1000
unique    10       3         3     3      4
top        3       1         3     2      3
freq     280     907       814   714    630

In [138]:
df.notna().sum()

laufkont    1000
laufzeit    1000
moral       1000
verw        1000
hoehe       1000
sparkont    1000
beszeit     1000
rate        1000
famges      1000
buerge      1000
wohnzeit    1000
verm        1000
alter       1000
weitkred    1000
wohn        1000
bishkred    1000
beruf       1000
pers        1000
telef       1000
gastarb     1000
kredit      1000
dtype: int64

In [139]:
df.isna().mean()

laufkont    0.0
laufzeit    0.0
moral       0.0
verw        0.0
hoehe       0.0
sparkont    0.0
beszeit     0.0
rate        0.0
famges      0.0
buerge      0.0
wohnzeit    0.0
verm        0.0
alter       0.0
weitkred    0.0
wohn        0.0
bishkred    0.0
beruf       0.0
pers        0.0
telef       0.0
gastarb     0.0
kredit      0.0
dtype: float64

In [140]:
df.notna().mean()

laufkont    1.0
laufzeit    1.0
moral       1.0
verw        1.0
hoehe       1.0
sparkont    1.0
beszeit     1.0
rate        1.0
famges      1.0
buerge      1.0
wohnzeit    1.0
verm        1.0
alter       1.0
weitkred    1.0
wohn        1.0
bishkred    1.0
beruf       1.0
pers        1.0
telef       1.0
gastarb     1.0
kredit      1.0
dtype: float64

In [141]:
df['missing_hoehe'] = df['hoehe'].isna().astype(int)

Indicator for missing

In [142]:
df['missing_hoehe']

0      0
1      0
2      0
3      0
4      0
      ..
995    0
996    0
997    0
998    0
999    0
Name: missing_hoehe, Length: 1000, dtype: int32

In [143]:
df['hoehe'] = df['hoehe'].fillna(df['hoehe'].median())

Used median instead of mean because mean is significantly affected by extreme values / outliers

In [144]:
df.loc[df.sample(frac=0.3, random_state=1).index, 'verw'] =  np.nan

sample() : randomly selects rows 
frac = 0.3 : selects 3% of the total rows
random_state = 1 : makes selection reproducible i.e. if we re-run the notebook same rows become missing like in SAS we had Seed=12345
.index : because after sampling we take their indexes
.loc : safely executes these commands

In [145]:
df['verw'].isna().sum()

300

We artificially introduced missing values

In [146]:
df['verw'] = df['verw'].cat.add_categories(['Missing'])

If Missing is not added as a cateory then filling it will give error

In [148]:
df['verw'] = df['verw'].fillna('Missing')

In [149]:
df['verw']

0            2
1            0
2      Missing
3      Missing
4            0
        ...
995    Missing
996    Missing
997    Missing
998          3
999          2
Name: verw, Length: 1000, dtype: category
Categories (11, object): [0, 1, 2, 3, ..., 8, 9, 10, 'Missing']

In [150]:
df['loan_to_age_ratio'] = df['hoehe'] / df['alter']

In [ ]:
df['loan_to_age_ratio'].head()

In [ ]:
#df.loc[df['alter'] > 50 ,'risk_flag'] = 1

In [151]:
df['risk_flag'] = (df['alter'] > 50).astype(int)

In [152]:
df['risk_flag']

0      0
1      0
2      0
3      0
4      0
      ..
995    0
996    0
997    0
998    1
999    0
Name: risk_flag, Length: 1000, dtype: int32

In [153]:
df['high_loan'] = (df['hoehe'] > 5000).astype(int)

Creating new columns

In [154]:
df['high_loan']

0      0
1      0
2      0
3      0
4      0
      ..
995    0
996    0
997    1
998    1
999    1
Name: high_loan, Length: 1000, dtype: int32

In [155]:
df['alter']

0      21
1      36
2      23
3      39
4      38
       ..
995    21
996    45
997    30
998    52
999    31
Name: alter, Length: 1000, dtype: int64

In [156]:
df['age_groups'] = pd.cut(df['alter'], bins = [18,30, 45, 60, 100], labels = ['18-30', '30-45', '45-60', '60+'])

Created a categorical variable by converting continuous to categorical using bins

In [157]:
df['age_groups']

0      18-30
1      30-45
2      18-30
3      30-45
4      30-45
       ...
995    18-30
996    30-45
997    18-30
998    45-60
999    30-45
Name: age_groups, Length: 1000, dtype: category
Categories (4, object): ['18-30' < '30-45' < '45-60' < '60+']

In [158]:
df[['age_groups', 'alter']]

    age_groups  alter
0        18-30     21
1        30-45     36
2        18-30     23
3        30-45     39
4        30-45     38
..         ...    ...
995      18-30     21
996      30-45     45
997      18-30     30
998      45-60     52
999      30-45     31

[1000 rows x 2 columns]

In [159]:
df.dtypes

laufkont                int64
laufzeit                int64
moral                   int64
verw                 category
hoehe                   int64
sparkont                int64
beszeit                 int64
rate                    int64
famges                  int64
buerge               category
wohnzeit                int64
verm                    int64
alter                   int64
weitkred             category
wohn                 category
bishkred                int64
beruf                category
pers                    int64
telef                   int64
gastarb                 int64
kredit                  int64
missing_hoehe           int32
loan_to_age_ratio     float64
risk_flag               int32
high_loan               int32
age_groups           category
dtype: object

In [160]:
df['long_term_loan'] = (df['laufzeit'] > 36).astype(int)

In [161]:
column_mapping = {
    'laufkont' : 'checking_status',
    'laufzeit' : 'duration_months',
    'moral' : 'credit_history',
    'hoehe' : 'credit_amount',
    'alter' : 'age_years',
    'verw' : 'purpose',
    'sparkont' : 'savings_amount',
    'beszeit' : 'employement_duration',
    'wohn' : 'housing_status',
    'kredit' : 'default_risk',
    'rate' : 'insallment_rate',
    'famges' : 'personal_status_sex',
    'buerge' : 'other_debtors',
    'wohnzeit' : 'residence_duration',
    'verm' : 'property',
    'weitkred' : 'other_installment_plans',
    'bishkred' : 'number_credits',
    'beruf' : 'job_type',
    'pers' : 'liable_people',
    'telef' : 'telephone',
    'gastarb' : 'foreign_worker'
}

In [162]:
df = df.rename(columns = column_mapping)

In [163]:
df.columns

Index(['checking_status', 'duration_months', 'credit_history', 'purpose',
       'credit_amount', 'savings_amount', 'employement_duration',
       'insallment_rate', 'personal_status_sex', 'other_debtors',
       'residence_duration', 'property', 'age_years',
       'other_installment_plans', 'housing_status', 'number_credits',
       'job_type', 'liable_people', 'telephone', 'foreign_worker',
       'default_risk', 'missing_hoehe', 'loan_to_age_ratio', 'risk_flag',
       'high_loan', 'age_groups', 'long_term_loan'],
      dtype='object')

In [164]:
df.head()

,checking_status,duration_months,credit_history,purpose,credit_amount,savings_amount,employement_duration,insallment_rate,personal_status_sex,other_debtors,...,liable_people,telephone,foreign_worker,default_risk,missing_hoehe,loan_to_age_ratio,risk_flag,high_loan,age_groups,long_term_loan
0,1,18,4,2,1049,1,2,4,2,1,...,2,1,2,1,0,49.952381,0,0,18-30,0
1,1,9,4,0,2799,1,3,2,3,1,...,1,1,2,1,0,77.750000,0,0,30-45,0
2,2,12,2,Missing,841,2,4,2,2,1,...,2,1,2,1,0,36.565217,0,0,18-30,0
3,1,12,4,Missing,2122,1,3,3,3,1,...,1,1,1,1,0,54.410256,0,0,30-45,0
4,1,12,4,0,2171,1,3,4,3,1,...,2,1,1,1,0,57.131579,0,0,30-45,0

In [165]:
df = df.rename(columns = {'employement_duration' : 'employment_duration'})

In [166]:
df = df.rename(columns = {'insallment_rate' : 'installment_rate'})

In [167]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 27 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   checking_status          1000 non-null   int64
 1   duration_months          1000 non-null   int64
 2   credit_history           1000 non-null   int64
 3   purpose                  1000 non-null   category
 4   credit_amount            1000 non-null   int64
 5   savings_amount           1000 non-null   int64
 6   employment_duration      1000 non-null   int64
 7   installment_rate         1000 non-null   int64
 8   personal_status_sex      1000 non-null   int64
 9   other_debtors            1000 non-null   category
 10  residence_duration       1000 non-null   int64
 11  property                 1000 non-null   int64
 12  age_years                1000 non-null   int64
 13  other_installment_plans  1000 non-null   category
 14  housing_status           1000 non-null   category
 15  number_credits           1000 non-null   int64
 16  job_type                 1000 non-null   category
 17  liable_people            1000 non-null   int64
 18  telephone                1000 non-null   int64
 19  foreign_worker           1000 non-null   int64
 20  default_risk             1000 non-null   int64
 21  missing_hoehe            1000 non-null   int32
 22  loan_to_age_ratio        1000 non-null   float64
 23  risk_flag                1000 non-null   int32
 24  high_loan                1000 non-null   int32
 25  age_groups               1000 non-null   category
 26  long_term_loan           1000 non-null   int32
dtypes: category(6), float64(1), int32(4), int64(16)
memory usage: 155.6 KB

# Type Conversion

In [185]:
df['credit_amount'] = pd.to_numeric(df['credit_amount'] , errors='coerce')

using to_numeric() function converts valid numbers to numeric and invalid strings to NaN thereby prevents crash

In [186]:
df['credit_amount'] = pd.to_numeric(df['credit_amount'] , errors='coerce').astype('Int64')

So while converting to numeric if there are missing values it get converted to NaN as discussed but as NaN are of float type so whole column also changes to type float so to prevent this we use astype('Int64') function along.

# Mapping Categories

In [195]:
df['foreign_worker'].unique()

array([2, 1], dtype=int64)

Must inspect then map correctly, **earlier got error due to incorrect mapping and the data got mutated**

In [196]:
df['foreign_worker'] = df['foreign_worker'].map({ 1 : 'yes' , 2 : 'no' })

In [197]:
df['foreign_worker'].unique()

array(['no', 'yes'], dtype=object)

map() function changes unmatched values to NaN whereas replace() function leaves unmatched values unchanged

In [198]:
df['foreign_worker'] = df['foreign_worker'].astype('category')

# Rules to follow for mapping
    1. Inspect unique values
    2. Map
    3. Convert to category
    4. Define order if needed

In [ ]:
#col = 'job_type'
#mapping  = {1: 'unskilled', 2: 'skilled', 3: 'highly_skilled', 4: 'management'}
#assert set(df[col].unique()) <= set(mapping.keys())

If mapping misses a value -> it raises AssetionError immediately

# Managing Duplicates and Data Integrity

In [199]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

Returns a boolean series, True if duplicate found, False if no duplicates

In [201]:
df.duplicated().sum()

0

In [202]:
df[df.duplicated()]

Empty DataFrame
Columns: [checking_status, duration_months, credit_history, purpose, credit_amount, savings_amount, employment_duration, installment_rate, personal_status_sex, other_debtors, residence_duration, property, age_years, other_installment_plans, housing_status, number_credits, job_type, liable_people, telephone, foreign_worker, default_risk, missing_hoehe, loan_to_age_ratio, risk_flag, high_loan, age_groups, long_term_loan]
Index: []

[0 rows x 27 columns]

In [203]:
df = df.drop_duplicates()

Returns a new DataFrame
Doesn't modify in place unless assigned

In [204]:
df.duplicated(subset=['credit_amount' , 'age_years'])

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

Checks duplicate on the provided subset of columns
Useful when say two customers have same loan amount and same age but different id's. So this helps in distinguishing whether it is a full row or a partial duplication.

In [ ]:
#df.duplicated(keep='first') --> default behaviour
#df.duplicated(keep='last')
#df.duplicated(keep=False) --> all duplicates are marked True and none is kept

# Data Integrity Checks

In [206]:
#Impossible values
df[df['age_years'] <= 0]

Empty DataFrame
Columns: [checking_status, duration_months, credit_history, purpose, credit_amount, savings_amount, employment_duration, installment_rate, personal_status_sex, other_debtors, residence_duration, property, age_years, other_installment_plans, housing_status, number_credits, job_type, liable_people, telephone, foreign_worker, default_risk, missing_hoehe, loan_to_age_ratio, risk_flag, high_loan, age_groups, long_term_loan]
Index: []

[0 rows x 27 columns]

In [207]:
df[df['credit_amount'] <= 0]

Empty DataFrame
Columns: [checking_status, duration_months, credit_history, purpose, credit_amount, savings_amount, employment_duration, installment_rate, personal_status_sex, other_debtors, residence_duration, property, age_years, other_installment_plans, housing_status, number_credits, job_type, liable_people, telephone, foreign_worker, default_risk, missing_hoehe, loan_to_age_ratio, risk_flag, high_loan, age_groups, long_term_loan]
Index: []

[0 rows x 27 columns]

In [208]:
#Unexpected Categories
df['purpose'].unique()

[2, 0, 'Missing', 3, 1, ..., 9, 6, 4, 8, 10]
Length: 11
Categories (11, object): [0, 1, 2, 3, ..., 8, 9, 10, 'Missing']

In [209]:
purpose_mapping = { 0 : 'others', 1 : 'car(new)', 2: 'car(used)', 3 : 'furniture/equiment',
                    4 : 'radio/television', 5 : 'domestic appliances', 6 : 'repairs', 7 : 'education',
                    8 : 'vacation', 9 : 'retraining', 10 : 'business'}

In [210]:
df['purpose'] = df['purpose'].map(purpose_mapping)

In [211]:
df['purpose'] = df['purpose'].astype('category')

In [212]:
set(df['purpose'].cat.categories)

{'business',
 'car(new)',
 'car(used)',
 'domestic appliances',
 'furniture/equiment',
 'others',
 'radio/television',
 'repairs',
 'retraining',
 'vacation'}

In [213]:
df.nunique()

checking_status              4
duration_months             33
credit_history               5
purpose                     10
credit_amount              923
savings_amount               5
employment_duration          5
installment_rate             4
personal_status_sex          4
other_debtors                3
residence_duration           4
property                     4
age_years                   53
other_installment_plans      3
housing_status               3
number_credits               4
job_type                     4
liable_people                2
telephone                    2
foreign_worker               2
default_risk                 2
missing_hoehe                1
loan_to_age_ratio          992
risk_flag                    2
high_loan                    2
age_groups                   4
long_term_loan               2
dtype: int64

If a column has only 1 unique value -> useless for modelling

In [214]:
df[['age_years', 'credit_amount']].describe()

        age_years  credit_amount
count  1000.00000         1000.0
mean     35.54200       3271.248
std      11.35267     2822.75176
min      19.00000          250.0
25%      27.00000         1365.5
50%      33.00000         2319.5
75%      42.00000        3972.25
max      75.00000        18424.0